### ISSUE TITLE
Permissions for verbose readout of ALS

### ISSUE THREAD

**Issue by lknik** [w3c/ambient-light#10]
Verbose readout of Ambient Light Sensors might create several issues from privacy perspective (e.g cross-domain communication, cross-device linking, profiling), consider also http://lukaszolejnik.com/SensorsPrivacyReport.pdf. 
In this view we should decide if ASL will be subject to permissions? 

An interesting idea is to expose a minimized readout using MediaQueries terminology (https://www.w3.org/TR/mediaqueries-4/#light-level) without permissions, and require them for more verbose readout. This would make most of the privacy issues much less conceivable.
I already discussed this in private with Tobie.

I believe privacy considerations should be proposed after deciding this, since this impacts them directly (in my current draft, I propose ASL should be subject to permissions).

**Comment by tobie** [comment]
ASL is subject to permission as are all sensors by default.

**Comment by lknik** [comment]
Hi,

You are right! Thanks.
So now I know what to write. But part of the question remains, can ALS provide MediaQueries-like readout.

**Comment by tobie** [comment]
I would suggest creating a dedicated LightLevelSensor for that.

**Comment by lknik** [comment]
Sounds good.

This leaves multiplies sensor APIs, but leaves it cleaner.

**Comment by tobie** [comment]
This seems resolved. Closing.
