### ISSUE TITLE
Light-level deferred to Media Queries Level 5

### ISSUE THREAD

**Issue by lknik** [w3c/ambient-light#12]
Light-level feature is deferred to Media Queries Level 5 [1].
Currently, ASL spec references MQ Level 4.

Does it highlight the need for a separate sensor with a discrete readout?

[1] https://github.com/w3c/csswg-drafts/blob/master/mediaqueries/deferred-for-level-5.txt

**Comment by anssiko** [comment]
The `light-level` CSS media feature is a composite of many values (for details, see https://github.com/w3c/csswg-drafts/issues/1727), while the [current light level] of the Ambient Light Sensor API is precisely what the [attribute name] also suggests, [illuminance].

That is to say, these features address different use cases and should coexist peacefully. I'm inclined to close this issue.

[current light level]: https://w3c.github.io/ambient-light/#current-light-level
[attribute name]: https://w3c.github.io/ambient-light/#dom-ambientlightsensor-illuminance
[illuminance]: https://en.wikipedia.org/wiki/Illuminance
