### ISSUE TITLE
Available in workers?

### ISSUE THREAD

**Issue by torgo** [w3c/ambient-light#16]
Question raised in [TAG f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2016/11-tokyo/agenda.md): is this API going to be available in workers and if so under what constraints? See also https://github.com/w3ctag/spec-reviews/issues/115.

**Comment by tobie** [comment]
Apparently that's a req of the TAG for Generic Sensor API for performance reasons (see #110). Thus, yes, though I would have preferred delaying it to a second version of the spec.

I need to figure the permission model for it. Pointers welcomed.

**Comment by torgo** [comment]
paging @slightlyoff

**Comment by alexshalamov** [comment]
This issue is not specific to ALS and there are already few duplicates related to exposing GS API based sensors to workers https://github.com/w3c/sensors/projects/5 (Expose sensors to workers). Closing issue for now.
