### ISSUE TITLE
Should we really redefine AmbientLightSensor.reading?

### ISSUE THREAD

**Issue by tobie** [w3c/ambient-light#17]
`Sensor.reading` is already defined in the Generic Sensor API as:

```webidl
interface Sensor {
   // ...
   readonly attribute SensorReading? reading;
};
```
`AmbientLightSensor` inherits from `Sensor` and `AmbientLightSensorReading` from `SensorReading`. It therefore seems redefining it isn't strictly necessary. Curious what the best practice is, here.

**Comment by anssiko** [comment]
This redundancy seems justified given it makes the spec more readable (to a wider audience than just us spec people and implementers) as a standalone piece. That said, I'd like to hear others' opinions.

**Comment by tobie** [comment]
On irc, @annevk seemed to suggest otherwise:

```
12:38 […] I think you don't have to redefine it
12:38 only use would be stating a more specific return value, right?
12:39 you only do it if you change the type
12:40 which is an anti-pattern, but legacy
```

**Comment by tobie** [comment]
@anssiko I think it's arguable both ways. The Sensor object is just a click away. And exposing the generic sensor API to a wider audience is also a very good thing imho, makes the consistency across APIs more obvious.

**Comment by dontcallmedom** [comment]
I would avoid redefining it if we don't have to; we can always make a note in the spec about where the `reading` attribute comes from

**Comment by dontcallmedom** [comment]
but @annevk comment seems to suggest that our approach to extensibility for `SensorReading` is not right

**Comment by annevk** [comment]
@dontcallmedom a subclass is not redefining the type. For IDL purposes that's the same type.

**Comment by annevk** [comment]
(`HTMLFormControlsCollection` is an example of an object where we change the return type of the `namedItem()` method. And one we don't want to repeat.)

**Comment by anssiko** [comment]
Thanks @annevk for chiming in. To clarify, I'm happy with whatever is the Right Thing (TM). @tobie feel free to implement when this issue is settled.
