### ISSUE TITLE
Is "frequency" available in ALS?

### ISSUE THREAD

**Issue by Honry** [w3c/ambient-light#18]
>7. If frequency is not null,
>    1. If sensor supports periodic reporting mode,
>        1. Set sensor_instance’s desired frequency to frequency.
>    2. Otherwise,
>        1. throw a TypeError.

> The Ambient Light Sensor has a single supported reporting mode which is "auto".

According to above spec description,  "TypeError" will be thrown when passing a "frequency" value to ALS, but implementation in [latest Chromium Canary](https://www.chromium.org/getting-involved/dev-channel) is opposite. @riju @tobie

**Comment by tobie** [comment]
Yes. I'm working on finding consensus around this topic. @pozdnyakov and @alexshalamov have provided implementation feedback which suggests not throwing is the right thing to do. I'm considering future compat implications right now. I'll be reporting on this issue both within the spec itself and in https://github.com/w3c/sensors/issues/126 over the upcoming weeks.

**Comment by Honry** [comment]
Oops, I made a duplicated ticket. Thanks for the comment @tobie, close this one and let's track this issue in w3c/sensors#126.
