### ISSUE TITLE
Auto reporting mode is not defined

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/ambient-light#19]
The spec states that ALS  only supports `auto` reporting mode.  However this term is not defined in the Generic Sensors API.

**Comment by anssiko** [comment]
Given the recent update, the reporting mode feature is now at risk (could be dropped):
https://w3c.github.io/sensors/#concepts-reporting-modes

If we keep it, we'll likely switch to an implementation specific reporting mode for this spec:
https://w3c.github.io/sensors/#implementation-specific

We'll update this spec shortly to align it with the recent changes in the Generic Sensor API it extends. Meanwhile, I'll keep this issue open.

**Comment by anssiko** [comment]
Fixed with #28.
