### ISSUE TITLE
AmbientLightSensor constructor cannot initialize illuminance

### ISSUE THREAD

**Issue by foolip** [w3c/ambient-light#24]
https://w3c.github.io/ambient-light/#ambient-light-sensor-interface

This seems like a bug, there should probably be an `AmbientLightSensorOptions` dictionary that includes `illuminance`.

**Comment by pozdnyakov** [comment]
think the `illuminance` attribute should rather be nullable. @tobie

**Comment by foolip** [comment]
That would be an orthogonal question, the problem is that it's current readonly so there's no way to set it to any value.

**Comment by tobie** [comment]
Well, that's by design. It's a getter to the value provided by the sensor.

**Comment by pozdnyakov** [comment]
@foolip what would be the use case for setting illuminance from the ctor? AFAIK it should just contain the latest AML sensor reading in `activated` state and be `null` in all the other states.

**Comment by foolip** [comment]
OK, I didn't follow the links, I assumed that the relationship between AmbientLightSensor and Sensor was like that between MessageEvent and Event, that both had constructors that should be able to set all of the members, and that the members never change. Not so.

**Comment by tobie** [comment]
That's the design we had initially, which probably explains why you got confused.
