### ISSUE TITLE
Consider making granularity of the data normative

### ISSUE THREAD

**Issue by cynthia** [w3c/ambient-light#63]
Discussed in the virtual TPAC discussion here: https://www.w3.org/2020/10/23-dap-minutes.html

Currently, the only implementation (Chromium) gates the sensor information through a step function of privacy/security reasons - would it make sense to consider making this behavior normative in the spec?

**Comment by jonathanKingston** [comment]
@cynthia are you able to explain a little further the granularity changes Chrome makes, I don't see much in the minutes or non normative in the spec text.

**Comment by sandandsnow** [comment]
Thank you @xfq for bringing this issue to our attention in PING via the privacy-tracker label. We are pleased to see that you are working to make the privacy mitigations normative in the spec.

**Comment by rakuco** [comment]
> @cynthia are you able to explain a little further the granularity changes Chrome makes, I don't see much in the minutes or non normative in the spec text.

This was discussed in #13 and the first Chromium commit is https://chromium-review.googlesource.com/c/chromium/src/+/1834346 (see also https://bugs.chromium.org/p/chromium/issues/detail?id=642731).

The idea is to:
* Round off the values we expose to the nearest 50 Lux (e.g. 0, 50, 100, 150 etc).
* Only fire a new reading event if the previous and current raw values differ significantly (we currently check if they differ by more than half the 50 Lux threshold).

**Comment by anssiko** [comment]
@jonathanKingston are you interested in joining our TPAC meeting https://github.com/w3c/devicesensors-wg/issues/47 as a guest for this and possibly other privacy topics of interest? I’ll follow up separately.

**Comment by cynthia** [comment]
Just to be on record, while it probably is very confusing, I don't work on Chrome - so I can't answer Chrome specific questions. The granularity quantization must have been discussed and recorded somewhere under the WG though.

**Comment by sandandsnow** [comment]
Checking in to see where things stand on this issue

**Comment by anssiko** [comment]
@sandandsnow thanks for checking. Most recently, we made the following resolution: 
> RESOLUTION: Make Ambient Light Sensor granularity of the data normative
https://www.w3.org/2021/10/29-dap-minutes.html#r02

Let us know if this satifies your request and we’ll update the spec to match the implementation in this regard.

@rakuco implemented this mitigation IIRC, so maybe he can spec this and loop in @sandandsnow for review.

**Comment by sandandsnow** [comment]
Thank you @anssiko. This is very helpful. Also, any idea when this resolution will be fully implemented?

**Comment by rakuco** [comment]
> any idea when this resolution will be fully implemented?

This is something in my to-do list. The spec changes aren't big, but I need to ask for input from people who reviewed the original mitigations that were added to Chrome years ago, as that work precedes my involvement with this spec and I don't fully remember how we reached those specific threshold values. I'd like to get this done by 2022 Q1.

**Comment by rakuco** [comment]
I've sent w3c/sensors#429 and #77 here to try to address this. The changes ended up being larger than just specifying a granularity value because Chrome specifies granularity _and_ checks if new readings differ enough from the current one to store them, and both are required.

Feedback is highly appreciated, especially because this is the first time I'm normatively specifying security related stuff so I'm assuming everything will explode in weird ways :-)

**Comment by rakuco** [comment]
> I've sent [w3c/sensors#429](https://github.com/w3c/sensors/pull/429) and #77 here to try to address this. The changes ended up being larger than just specifying a granularity value because Chrome specifies granularity _and_ checks if new readings differ enough from the current one to store them, and both are required.
> 
> Feedback is highly appreciated, especially because this is the first time I'm normatively specifying security related stuff so I'm assuming everything will explode in weird ways :-)

The PRs above have been merged, so I think we're finally done here!
