### ISSUE TITLE
I can't use it for my time telling bot project

### ISSUE THREAD

**Issue by Aayam555** [w3c/ambient-light#69]
I can't use it because my chrome browser is not supporting it I guess So, I want some help about this

This is the website link: https://tonytellstime.netlify.app/

**Comment by anssiko** [comment]
This API is behind the #enable-generic-sensor-extra-classes flag in chrome://flags You need to turn on this flag for the time being. For Chrome status, see https://www.chromestatus.com/feature/5298357018820608

We welcome feedback from web developers on experiments and projects using this API via https://github.com/w3c/ambient-light/issues/64 to help move this spec forward. Feel free to link your project there, and if not obvious, add a short description of the use case the API enables for your project (and wouldn’t be possible without it).
